/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Versioned liveness (prefer unversioned GET /health for probes) */
        get: operations["health_v1_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/offers/{offer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get offer detail from local/Redis offer store */
        get: operations["get_offer_api_v1_offers__offer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness checks (Redis required in staging/production) */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search flights (server-side filter/sort/page) */
        post: operations["search_flights_api_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unversioned liveness probe
         * @description Liveness for platform/uptime probes (no dependency checks).
         */
        get: operations["root_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DependencyStatus */
        DependencyStatus: {
            /** Detail */
            detail?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error" | "skipped";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Money */
        Money: {
            /**
             * Amount
             * @description Decimal string, e.g. '542.30'
             */
            amount: string;
            /** Currency */
            currency: string;
        };
        /**
         * OfferPublic
         * @description Client-facing offer (no provider_payload).
         */
        OfferPublic: {
            /** Baggage Summary */
            baggage_summary?: string | null;
            /**
             * Cabin Class
             * @enum {string}
             */
            cabin_class: "economy" | "premium_economy" | "business" | "first";
            /** Expires At */
            expires_at?: string | null;
            /** Id */
            id: string;
            price: components["schemas"]["Money"];
            /**
             * Provider
             * @enum {string}
             */
            provider: "mock" | "amadeus" | "duffel";
            /** Slices */
            slices: components["schemas"]["Slice"][];
            /** Validating Airline */
            validating_airline: string;
        };
        /** Passengers */
        Passengers: {
            /**
             * Adults
             * @default 1
             */
            adults: number;
            /**
             * Children
             * @default 0
             */
            children: number;
            /**
             * Infants
             * @default 0
             */
            infants: number;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /** Checks */
            checks?: {
                [key: string]: components["schemas"]["DependencyStatus"];
            };
            /** Environment */
            environment: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
        };
        /** SearchFilters */
        SearchFilters: {
            /** Airlines */
            airlines?: string[] | null;
            /** Max Duration Minutes */
            max_duration_minutes?: number | null;
            /** Max Price */
            max_price?: number | null;
            /** Max Stops */
            max_stops?: number | null;
        };
        /** SearchRequest */
        SearchRequest: {
            /**
             * Cabin Class
             * @default economy
             * @enum {string}
             */
            cabin_class: "economy" | "premium_economy" | "business" | "first";
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /**
             * Departure Date
             * Format: date
             */
            departure_date: string;
            /** Destination */
            destination: string;
            filters?: components["schemas"]["SearchFilters"] | null;
            /** Origin */
            origin: string;
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 20
             */
            page_size: number;
            passengers?: components["schemas"]["Passengers"];
            /** Return Date */
            return_date?: string | null;
            /**
             * Sort
             * @default price_asc
             * @enum {string}
             */
            sort: "price_asc" | "price_desc" | "duration_asc" | "departure_asc";
            /**
             * Trip Type
             * @enum {string}
             */
            trip_type: "one_way" | "round_trip";
        };
        /** SearchResponse */
        SearchResponse: {
            /**
             * Cache
             * @enum {string}
             */
            cache: "HIT" | "MISS";
            /** Cached At */
            cached_at: string;
            /** Currency */
            currency: string;
            /** Offers */
            offers: components["schemas"]["OfferPublic"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /**
             * Price Disclaimer
             * @default Prices are estimates and may change before booking.
             */
            price_disclaimer: string;
            /** Request Id */
            request_id?: string | null;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /** Total */
            total: number;
        };
        /** Segment */
        Segment: {
            /**
             * Arrive At
             * Format: date-time
             */
            arrive_at: string;
            /**
             * Depart At
             * Format: date-time
             */
            depart_at: string;
            /** Destination */
            destination: string;
            /** Duration Minutes */
            duration_minutes: number;
            /** Flight Number */
            flight_number: string;
            /** Marketing Carrier */
            marketing_carrier: string;
            /** Origin */
            origin: string;
        };
        /** Slice */
        Slice: {
            /**
             * Direction
             * @enum {string}
             */
            direction: "outbound" | "inbound";
            /** Duration Minutes */
            duration_minutes: number;
            /** Segments */
            segments: components["schemas"]["Segment"][];
            /** Stops */
            stops: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_offer_api_v1_offers__offer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description One or more required dependencies failed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search_flights_api_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
